server:
  port: 8081
  servlet:
    context-path: /account-service

spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:accountdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true